#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d 一 二 三 四 五 六
bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         0
bspc config window_gap           0
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config focused_border_color "#000000"
bspc config normal_border_color "#000000"
bspc config presel_feedback_color "#121212"
bspc config focus_follows_pointer true

mpd
xset s off &
xset -dpms &
# xset r rate 200 50 &
# setxkbmap -layout "br,ru" -option "grp:alt_shift_toggle" &
setxkbmap br &
# xsetroot -mod 14 14 -bg "#000000" -fg "#3b3b3b"
feh --bg-fill /home/edu/img/wall/autumn-train.jpg &
