#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六

bspc config border_width         0
bspc config window_gap           0
bspc config top_padding         50
bspc config bottom_padding      50
bspc config left_padding        50
bspc config right_padding       50
bspc config focused_border_color "#000000"
bspc config normal_border_color "#000000"
bspc config presel_feedback_color "#121212"
bspc config focus_follows_pointer true

mpd
xset s off &
xset -dpms &
feh --bg-fill /home/edu/img/wall/eva-light.png &
setxkbmap -layout "br,ru" -option "grp:alt_shift_toggle" &
